language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
branches:
  only:
    - develop

before_install:
  - cd tests

script:
  - php phpunit.phar -c phpunit-travis.xml
  
notifications:
  email:
    - kelmadics@gmail.comgit statu
