<?php
# The global config is the default global config definitions
# Do not edit this file! You can override the configurations in config/local.php
return array(
    'xdebug' => array(
        'trace_log'  => '/tmp/fdldebug', # Path for trace log file for XDEBUG
        'trace_file' => 'fdltrace',             # File name for XDEBUG trace file
    ),
    'writer'     => 'var_dump',               # default writer. Available writers ('var_dump')
    'conditions' => array('boolean', 'range') # Registered conditions
);
