<?php
# This config is the default global configuration definitions
# Do not edit this file! You can override the configurations in config/local.php
# or by returning an array of configurations to variable $fdldebug_config_file
return array(
    'xdebug' => array(
        'trace_output_dir'         => '/tmp/fdldebug',        # Path for trace log file for XDEBUG
        'trace_output_name'        => 'fdltrace',             # File name for XDEBUG trace file
        'trace_format'             => 0,
        'trace_enable_trigger'     => 1,
        'collect_assignments'      => 1,
        'var_display_max_data'     => 130,
        'var_display_max_depth'    => 5,
        'var_display_max_children' => 200,
        'collect_params'           => 2,
        'collect_return'           => 0,
        'show_mem_delta'           => 0,
    ),
    'writer'     => 'generic_output',           # Default writer. Available writers ('generic_output'). Using FQNS also qualifies
    'conditions' => array(                      # Registered conditions. Using FQNS also qualifies
        'boolean',
        'loop_range',
        'loop_from',
    ),
    'debug_prefixes'   => array(                # Declaration of debug prefixes for callable methods. Example printDebugTrace()
        'pr',
        'print',
        'loopFromFlush'
    ),
    'debug_extensions' => array(                # Extensions for FdlDebug. Use FQNS to declare new extension
        'loop_from',
        'xdebug',
    ),
);
